export const ERROR = 'ERROR'

export const CONNECTION_CONNECTED = 'CONNECTION_CONNECTED'
export const CONNECTION_DISCONNECTED = 'CONNECTION_DISCONNECTED'

export const DELEGATE = 'DELEGATE'
export const DELEGATE_RETURNED = 'DELEGATE_RETURNED'

export const SIGN_DELEGATE = 'SIGN_DELEGATE'
export const SIGN_DELEGATE_RETURNED = 'SIGN_DELEGATE_RETURNED'

export const SAVE_DELEGATE = 'SAVE_DELEGATE'
export const SAVE_DELEGATE_RETURNED = 'SAVE_DELEGATE_RETURNED'

export const GET_BALANCE = 'GET_BALANCE'
export const BALANCE_RETURNED = 'BALANCE_RETURNED'

export const GET_DELEGATEE_BALANCE = 'GET_DELEGATEE_BALANCE'
export const DELEGATEE_BALANCE_RETURNED = 'DELEGATEE_BALANCE_RETURNED'
